# Spring properties
spring:
  application:
     name: returnparam-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
