spring:
  application:
    name: account-service
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://115.159.199.121:3306/database
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: change
    key-password: change

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
#  instance:
#    preferIpAddress: true
#    ipAddress: 115.159.199.121

ribbon:
  eureka:
    enabled: true
