# Spring properties
spring:
  sleuth:
    enabled: true
    sampler: 1
  zipkin:
    base-url: http://115.159.199.121:9411
  application:
     name: complicated-client-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
#  instance:
#    preferIpAddress: true
#    ipAddress: 115.159.199.121

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
