# Spring properties
spring:
  sleuth:
    enabled: true
    sampler: 1
  zipkin:
      base-url: http://115.159.199.121:9411
  application:
     name: complicated-client-service
  cloud:
    inetutils:
      preferredNetworks: microservicedemo_backend_network

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://nameserver:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
