# Spring properties
spring:
  application:
     name: trace-callback-service
  cloud:
    inetutils:
      preferredNetworks: microservicedemo_backend_network

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://nameserver:1111/eureka/
  # instance:
  #   hostname: tracecallback
  #   preferIpAddress: false

# HTTP Server
server:
  port: 6789   # HTTP (Tomcat) port

# ribbon:
#   eureka:
#     enabled: true
