# Spring properties
spring:
  application:
     name: trace-callback-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://nameserver:1111/eureka/

# HTTP Server
server:
  port: 6789   # HTTP (Tomcat) port

# ribbon:
#   eureka:
#     enabled: true
