# Spring properties
spring:
  application:
     name: api-gateway-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 9000   # HTTP (Tomcat) port