spring:
  application:
    name: apiGateway-service
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://115.159.0.12:3306/campusqa?characterEncoding=utf-8
    username: campusqa
    password: campusqa
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: change
    key-password: change

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    # fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost

ribbon:
  eureka:
    enabled: true
