spring:
  application:
    name: apiGateway-service
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://115.159.199.121:3306/database
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver

# Disable Hystrix timeout globally (for all services)
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: change
    key-password: change

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    # fetchRegistry: false
    serviceUrl:
      defaultZone: http://115.159.199.121:1111/eureka/
  instance:
    hostname: localhost

ribbon:
  eureka:
    enabled: true
