# Spring properties
spring:
  application:
    name: simple-client-service
  cloud:
    inetutils:
      preferredNetworks: microservicedemo_backend_network

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://nameserver:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

ribbon:
  eureka:
    enabled: true
