# Spring properties
spring:
  application:
     name: simple-client-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://nameserver:1111/eureka/
  instance:
    preferIpAddress: true

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

ribbon:
  eureka:
    enabled: true
