# Spring properties
spring:
  application:
     name: simple-client-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      # defaultZone: http://115.159.199.121:1111/eureka/
      defaultZone: http://localhost:1111/eureka/
  # instance:
  #   preferIpAddress: true
  #   ipAddress: 115.159.199.121

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

ribbon:
  eureka:
    enabled: true
