server:
  port: 5678
spring:
  application:
    name: sidecar

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

sidecar:
  port: 1111
  health-uri: http://localhost:8000/health.json