server:
  port: 5678
spring:
  application:
    name: sidecar

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

sidecar:
  port: 8000
  home-page-uri: http://115.159.199.121:8000/number
  health-uri: http://115.159.199.121:8000/health
